### ISSUE TITLE
Multiple Users with different directory support

### ISSUE THREAD

**Issue by camjac251** [koro666/archive#2]
Is it possible to use this with multiple users? I was planning to use nginx FancyIndex with `root /directory/to/$remote_user` to allow 6-7 users to login and only allow them access to their directory that has symlinks inside to files/folders they can access.
Is it possible to add multiple users and assign them a root subfolder?
 I really like the design of this app. It does things that nginx fancy index could never do.

**Comment by koro666** [comment]
The only time the app cares about users is when it checks if `REMOTE_USER` is in the list of editor users to know if it should show the edition UI in the gallery. For the rest, all checks and routing are handled within nginx without ever reaching the app.

In particular, it does not obey — or even know about — the nginx root. But as I said, since nginx handles all the routing, there would be nothing preventing you from defining one exported directory per user in `configuration.py`, and using nginx configuration trickery to only allow authentication by that user to `/browse/$remote_user` or something.
